---

#- name: reenable node exporter service
#  command: systemctl reenable prometheus-node-exporter.service
#
#- name: reinit node exporter
#  command: initctl reload-configuration

- name: restart node exporter
  service:
    name: node_exporter
    state: restarted