---

prometheus_version: 2.42.0
prometheus_service_reload: true

prometheus_user: prometheus
prometheus_group: prometheus

prometheus_global_scrape_interval: 15s
prometheus_global_evaluation_interval: 15s
prometheus_global_scrape_timeout: 10s
prometheus_self_scrape_interval: "{{ prometheus_global_scrape_interval }}"
prometheus_self_evaluation_interval: "{{ prometheus_global_scrape_interval }}"

prometheus_release_name: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_root_dir: /opt/prometheus/
prometheus_dist_dir: "/tmp/prom"
prometheus_file_sd_config_dir: "{{ prometheus_config_dir }}/clients"
prometheus_config_dir: /etc/prometheus
prometheus_log_dir: /var/log/prometheus
prometheus_pid_path: /var/run/prometheus.pid
prometheus_db_dir: /var/lib/prometheus


