---
# tasks file for elasticsearch-kibana
- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add elasticsearch repository
  ansible.builtin.yum_repository:
    name: "elasticsearch"
    description: "Elasticsearch repository for 8.x packages"
    file: elasticsearch
    baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: yes
    enabled: 0

- name: Add kibana repository
  ansible.builtin.yum_repository:
    name: "kibana-8.x"
    description: "Kibana repository for 8.x packages"
    file: kibana
    baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: yes
    enabled: 1

- name: install elasticsearch from rpm
  ansible.builtin.yum:
    name: elasticsearch
    state: present
    enablerepo: "elasticsearch"
    #register: install_elastic
    #notify:
- name: Enable Service Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

- name: install kibana from rpm
  ansible.builtin.yum:
    name: kibana
    state: present
    enablerepo: "elasticsearch"

- name: Enable Service kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: create elasticsearch config
  template:
    src: etc/elastic.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0640
  notify:
    - restart elasticsearch

- name: create elasticsearch jvm config
  template:
    src: etc/jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
  notify:
    - restart elasticsearch

- name: create kibana config
  template:
    src: etc/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  notify:
    - restart kibana
